// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:budget_app/forms/add_template.dart' as prefix3;
import 'package:budget_app/models/category.dart' as prefix1;
import 'package:budget_app/models/model.dart' as prefix4;
import 'package:budget_app/models/wallet.dart' as prefix5;
import 'package:budget_app/reflector.dart' as prefix0;
import 'package:budget_app/widgets/category_widget.dart' as prefix2;
import 'package:budget_app/widgets/default_widget.dart' as prefix6;
import 'package:budget_app/widgets/wallet_widget.dart' as prefix7;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[],
      null,
      null,
      <Type>[
        prefix1.CategoryModel,
        prefix2.CategoryWidget,
        prefix3.AddTemplateState,
        prefix4.Model,
        prefix5.WalletModel,
        prefix6.DefaultWidget,
        prefix7.WalletWidget
      ],
      7,
      {},
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
